# Generated by Django 3.2.4 on 2021-06-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20210609_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.TextField(default=1623240128.5854878),
        ),
        migrations.AlterField(
            model_name='place',
            name='created_at',
            field=models.TextField(default=1623240128.5854878),
        ),
        migrations.AlterField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='place', to='place.Tag'),
        ),
    ]
