# Generated by Django 3.2.4 on 2021-06-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_alter_relationship_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='created_at',
            field=models.TextField(default=1623480469.9960277),
        ),
    ]
